name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Patch Jekyll Config
      run: |
        echo "baseurl: /music-auto-tagging" >> _config.yml
        echo "url: http://$GITHUB_ACTOR.github.io" >> _config.yml
      env:
         GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

    - name: Build
      uses: agentd00nut/jekyll-build-optional-deploy-gh-pages@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        DEPLOY_SITE: false
        REMOVE_GEMLOCK: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.8.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site
